# Generated by Django 4.1.3 on 2022-12-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('start_year', models.DateTimeField(max_length=100)),
                ('passedout_year', models.DateTimeField(max_length=100)),
                ('typeof_college', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
