# Generated by Django 4.1.3 on 2023-01-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
